controller_manager:
  ros__parameters:
    update_rate: 20 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

steering_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint
      - rear_left_steering_joint
      - rear_right_steering_joint

velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
